sudo: required
services:
  - docker

before_install:
  - docker build -t baicham/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baicham/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-939813658752"
  bucket_path: "frontend"
  on:
    branch: "master"
  