#name: "Deploy to AWS Elastic Beanstalk"
#on: workflow_dispatch
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@v4
#
#      - name: Set version label
#        run: echo "VERSION_LABEL=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
#
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v22
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          region: "us-east-2"
#          application_name: "docker"
#          environment_name: "Docker-env"
#          existing_bucket_name: ${{ secrets.ELASTIC_BEAN_STALK_S3 }}
#          version_label: ${{ env.VERSION_LABEL }}
#          deployment_package: deploy.zip
#
