name: 'Build and Run Docker image'

on:
  push:
    branches:
      - '**'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Pu
      sh Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: baicham/docker-react:latest
          push: false
      
      - name: Run Docker container
        run: docker run -e CI=true baicham/docker-react npm run test
