name: "Test"
on:
  workflow_call:
  
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Check formatting Errors
        run: npm run format
      
      - name: Check ESLint Errors
        run: npm run lint
      
      - name: Check for Type Errors
        run: npm run typecheck
        
      - name: Build project
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-action@v3
        with:
          name: build
          path: .next/
          
      - name: Run unit test
        run: npm run test
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: coverage/
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cham207388/docker-k8-complete-guide
      
      - name: Install Playwright Browser
        run: npx playwright install -with-deps
          
      - name: Run e2e
        run: npm run test:e2e
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload-file-path: "./.github/utils/test-failure-payload-slack.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  
